### ISSUE TITLE
tblastn segmentation fault

### ISSUE THREAD

**Issue by rpetit3** [bactopia/bactopia-ap#6]
```
Command exit status:
  139

Command output:
  (empty)

Command error:
  .command.sh: line 40:    32 Segmentation fault      (core dumped) tblastn -db S.190206.00513 -query proteins.fasta -evalue 0.0001 -num_threads 4 -outfmt '6 qseqid qlen qstart qend sseqid slen sstart send length evalue bitscore pident nident mismatch gaps qcovs qcovhsp' -qcov_hsp_perc 50 >> blast/proteins/proteins.txt
```

maybe related to this: https://www.biostars.org/p/16729/

**Comment by rpetit3** [comment]
I think it may have been related to `-num_threads`, after switching to parallel in https://github.com/bactopia/bactopia-ap/commit/c08a0ab7563bb8bd4b505daf7759a715cf74e4fd the issues seems to have disappeared

**Comment by 18616831168** [comment]
> I think it may have been related to `-num_threads`, after switching to parallel in [c08a0ab](https://github.com/bactopia/bactopia/commit/c08a0ab7563bb8bd4b505daf7759a715cf74e4fd) the issues seems to have disappeared

Hi,rpetit3,  sorry that I don't know how to switching to parallel in c08a0ab. Can you describe it in more detail? thanks a lot .

**Comment by 18616831168** [comment]
[1]+ segmentation fault               nohup tblastn -query /public/data/baiyl/protdb/protozoon_uniprot.fasta -out Homology.blast -db ../RepeatMasker/repeat_merge_nolow_nois/Cryptocaryon.fasta.masked -num_threads 10 -max_hsps 1 -outfmt 6 -db_gencode 6

**Comment by rpetit3** [comment]
Hello @18616831168 

Are you getting this error running Bactopia? To use `parallel` with tblastn you will want to do something like:

```
        parallel --gnu --plain -j !{task.cpus} --recstart '>' -N 1 --pipe \
        tblastn -db !{sample} \
                -outfmt 15 \
                -evalue 0.0001 \
                -qcov_hsp_perc !{params.qcov_hsp_perc} \
                -query - \
                -out temp_json/${name}_{#}.json
```

**Comment by 18616831168** [comment]
> Hello @18616831168
> 
> Are you getting this error running Bactopia? To use `parallel` with tblastn you will want to do something like:
> 
> ```
>         parallel --gnu --plain -j !{task.cpus} --recstart '>' -N 1 --pipe \
>         tblastn -db !{sample} \
>                 -outfmt 15 \
>                 -evalue 0.0001 \
>                 -qcov_hsp_perc !{params.qcov_hsp_perc} \
>                 -query - \
>                 -out temp_json/${name}_{#}.json
> ```

thank you so much !  I will try
